### ISSUE TITLE
Build error on 0.1.4

### ISSUE THREAD

**Issue by ActionNerd** [kelly/node-i2c#20]
When executing npm install as root, ran into the issue below.  Here is my package.json:

{
  "name": "hello-world",
  "description": "hello world test app",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "express": "3.x",
    "ejs": "_",
    "pi-blaster.js": "_",
    "i2c": "*"
  }
}

> i2c@0.1.4 install /var/www2/node_modules/i2c
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.11.3/node-v0.11.3.tar.gz
gyp http 200 http://nodejs.org/dist/v0.11.3/node-v0.11.3.tar.gz
make: Entering directory `/var/www2/node_modules/i2c/build'
  CXX(target) Release/obj.target/i2c/src/i2c.o
../src/i2c.cc: In function âv8::Handle<v8::Value> ReadBlock(const v8::Arguments&)â:
../src/i2c.cc:128:16: error: expected primary-expression before â*â token
../src/i2c.cc:128:17: error: âbufferâ was not declared in this scope
make: *** [Release/obj.target/i2c/src/i2c.o] Error 1
make: Leaving directory`/var/www2/node_modules/i2c/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:103:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.6.11+
gyp ERR! command "node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www2/node_modules/i2c
gyp ERR! node -v v0.11.3
gyp ERR! node-gyp -v v0.9.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by rzr** [comment]
Is this issue still relevant on latest @abandonware's fork ?

https://libraries.io/npm/@abandonware%2Fi2c/usage

Relate-to: https://github.com/kelly/node-i2c/issues/97
