### ISSUE TITLE
Does not register CoffeeScript

### ISSUE THREAD

**Issue by tvalletta** [kelly/node-i2c#58]
/home/pi/noderocket/mpu-6050/node_modules/i2c/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210
          throw new Error("Use CoffeeScript.register() or require the coffee-s
                ^
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object.base.(anonymous function) [as .coffee] (/home/pi/noderocket/mpu-6050/node_modules/i2c/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210:17)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/pi/noderocket/mpu-6050/node_modules/i2c/main.js:2:11)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/pi/noderocket/mpu-6050/custom-driver/mpu6050.js:32:11)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/pi/noderocket/mpu-6050/custom-mpu-6050.js:1:77)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by kelly** [comment]
Should be fixed now in the latest version.
