### ISSUE TITLE
Problem talking to multiple i2c devices

### ISSUE THREAD

**Issue by mofux** [kelly/node-i2c#7]
Hi,

after the update the i2c address has to be passed to the constructor when initialising a new i2c device. Unfortunately this does not account for talking to multiple i2c devices:

``` javascript
var i2c = require('i2c');
var device1 = new i2c(0x5, {device: '/dev/i2c-0', debug: false});
// imagine device 1 would always return 1 if I read a byte and device 2 would always return 2
device1.readByte(console.log);   // result: 1
var device2 = new i2c(0x6, {device: '/dev/i2c-0', debug: false});
device2.readByte(console.log);   // result: 2
device1.readByte(console.log);   // result: 2 <-- wrong, should be 1
```

Is this behaviour intended? If so, what would be the correct way to change the i2c address after initialisation?

**Comment by amejias101** [comment]
is there an update to this?

**Comment by phixMe** [comment]
I am having similar issues. 
I get a memory leak if I try this:

var device1 = new i2c(0x70, {device: '/dev/i2c-1', debug: false});
var device2 = new i2c(0x70, {device: '/dev/i2c-6', debug: false});

Has anybody had trouble with this?

**Comment by phixMe** [comment]
I am still having a show stopping bug related to this.

Here is my error:
ERROR: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
ERROR: Trace
    at process.addListener (events.js:160:15)
    at process.on.process.addListener (node.js:802:26)
    at new i2c (/home/root/.node_app_slot/node_modules/node-BNO055/node_modules/i2c/lib/i2c.coffee:34:15)
